[package]
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
keywords = ["http", "curl", "httpie"]
license = "MIT"
description = "A command-line HTTP tool."
name = "rural"
repository = "https://github.com/saghm/rural"
version = "0.1.0"

[dependencies]
clap = "2.19.3"
hyper = "0.9.14"
