[package]
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
description = "User-friendly command-line HTTP tool."
documentation = "https://github.com/saghm/rural"
homepage = "https://github.com/saghm/rural"
keywords = ["http", "curl", "httpie"]
license = "MIT"
name = "rural"
repository = "https://github.com/saghm/rural"
version = "0.6.0"

[dependencies]
clap = "2.20.0"
colored = "1.4.0"
json-color = "0.3.0"
lazy_static = "0.2.2"
regex = "0.2.1"
reqwest = "0.2.0"
serde_json = "0.8.4"
