[package]
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
description = "User-friendly command-line HTTP tool."
documentation = "https://github.com/saghm/rural"
homepage = "https://github.com/saghm/rural"
keywords = ["http", "curl", "httpie"]
license = "MIT"
name = "rural"
readme = "README.md"
repository = "https://github.com/saghm/rural"
version = "0.7.1"

[dependencies]
clap = "2.24.2"
colored = "1.5.1"
json-color = "0.6.0"
lazy_static = "0.2.8"
regex = "0.2.2"
reqwest = "0.6.2"
serde_json = "1.0.2"
