[package]
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
description = "A command-line HTTP tool."
keywords = ["http", "curl", "httpie"]
license = "MIT"
name = "rural"
repository = "https://github.com/saghm/rural"
version = "0.1.0"

[dependencies]
clap = "2.19.3"
hyper = "0.9.14"
lazy_static = "0.2.2"
regex = "0.2.0"
