[package]
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
description = "User-friendly command-line HTTP tool."
documentation = "https://github.com/saghm/rural"
homepage = "https://github.com/saghm/rural"
keywords = ["http", "curl", "httpie"]
license = "MIT"
name = "rural"
repository = "https://github.com/saghm/rural"
version = "0.6.3"

[dependencies]
clap = "2.20.5"
colored = "1.4.1"
json-color = "0.5.0"
lazy_static = "0.2.4"
regex = "0.2.1"
reqwest = "0.4.0"
serde_json = "0.9.9"
